apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: sequifi
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: sequifi-dev-autopilot
          serviceAccountRef:
            name: web-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: sequifi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: sequifi-dev-app-key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: sequifi-dev-db-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: sequifi-dev-redis-auth
