apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-api
  namespace: sequifi
  annotations:
    iam.gke.io/gcp-service-account: sequifi-dev-web-api@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: sequifi
  annotations:
    iam.gke.io/gcp-service-account: sequifi-dev-worker@PROJECT_ID.iam.gserviceaccount.com
